image:
  file: .gitpod.Dockerfile

# exposed ports
ports:
- port: 8080
  onOpen: open-preview
  # onOpen: ignore

vscode:
  extensions:
    - ms-azuretools.vscode-docker@1.8.1:xuHtLS23Q5czFwYH7grcCQ==


# start up tasks
tasks:
  # init: Will be executed one time when creating a workspace, command: will be exected each time you open workspace
  - init: |
      composer update
      composer create-project --prefer-dist yiisoft/yii2-app-basic ./
      mysql -e "CREATE DATABASE IF NOT EXISTS yii2basic;"
      chmod +x ./yii
      chmod +x ./tests/bin/yii
    command: |
      sudo service mysql restart
      ./tests/bin/yii migrate --interactive=0
      ./yii migrate --interactive=0
      ./vendor/bin/codecept build
      ./tests/bin/yii serve
  - command: gp await-port 8080 && ./vendor/bin/codecept run --coverage
  # - command: gp await-port 8080 && gp preview $(gp url 8080)
